### ISSUE TITLE
Incorrect calculation in TimeSpanPAL in Example 8B

### ISSUE THREAD

**Issue by richq** [Etron-RA/RetroAchievements#1]
Hey, thanks for the tutorials! I spotted a bug in one of them, the following is wrong in the World Speedrun:

`function TimeSpanPAL(minutes, seconds, frames) => minutes * 2500 + seconds * 50 + frames`

it should be:

`function TimeSpanPAL(minutes, seconds, frames) => minutes * 3000  + seconds * 50 + frames`

Since even though it is PAL, there are still 60 seconds in a minute ;) 60 x 50 = 3000

**Comment by Etron-RA** [comment]
Nice catch, I've updated the code in the example. Glad you are finding the tutorials useful, let me know if you spot any other issues.
